# frozen_string_literal: true

module Merge
  module Accounting
    class ExpenseReports
      class ExpenseReportsLinesListRequestExpand
        ACCOUNT = "account"
        ACCOUNT_COMPANY = "account,company"
        ACCOUNT_COMPANY_CONTACT = "account,company,contact"
        ACCOUNT_COMPANY_CONTACT_TAX_RATE = "account,company,contact,tax_rate"
        ACCOUNT_COMPANY_TAX_RATE = "account,company,tax_rate"
        ACCOUNT_CONTACT = "account,contact"
        ACCOUNT_CONTACT_TAX_RATE = "account,contact,tax_rate"
        ACCOUNT_EMPLOYEE = "account,employee"
        ACCOUNT_EMPLOYEE_COMPANY = "account,employee,company"
        ACCOUNT_EMPLOYEE_COMPANY_CONTACT = "account,employee,company,contact"
        ACCOUNT_EMPLOYEE_COMPANY_CONTACT_TAX_RATE = "account,employee,company,contact,tax_rate"
        ACCOUNT_EMPLOYEE_COMPANY_TAX_RATE = "account,employee,company,tax_rate"
        ACCOUNT_EMPLOYEE_CONTACT = "account,employee,contact"
        ACCOUNT_EMPLOYEE_CONTACT_TAX_RATE = "account,employee,contact,tax_rate"
        ACCOUNT_EMPLOYEE_PROJECT = "account,employee,project"
        ACCOUNT_EMPLOYEE_PROJECT_COMPANY = "account,employee,project,company"
        ACCOUNT_EMPLOYEE_PROJECT_COMPANY_CONTACT = "account,employee,project,company,contact"
        ACCOUNT_EMPLOYEE_PROJECT_COMPANY_CONTACT_TAX_RATE = "account,employee,project,company,contact,tax_rate"
        ACCOUNT_EMPLOYEE_PROJECT_COMPANY_TAX_RATE = "account,employee,project,company,tax_rate"
        ACCOUNT_EMPLOYEE_PROJECT_CONTACT = "account,employee,project,contact"
        ACCOUNT_EMPLOYEE_PROJECT_CONTACT_TAX_RATE = "account,employee,project,contact,tax_rate"
        ACCOUNT_EMPLOYEE_PROJECT_TAX_RATE = "account,employee,project,tax_rate"
        ACCOUNT_EMPLOYEE_TAX_RATE = "account,employee,tax_rate"
        ACCOUNT_PROJECT = "account,project"
        ACCOUNT_PROJECT_COMPANY = "account,project,company"
        ACCOUNT_PROJECT_COMPANY_CONTACT = "account,project,company,contact"
        ACCOUNT_PROJECT_COMPANY_CONTACT_TAX_RATE = "account,project,company,contact,tax_rate"
        ACCOUNT_PROJECT_COMPANY_TAX_RATE = "account,project,company,tax_rate"
        ACCOUNT_PROJECT_CONTACT = "account,project,contact"
        ACCOUNT_PROJECT_CONTACT_TAX_RATE = "account,project,contact,tax_rate"
        ACCOUNT_PROJECT_TAX_RATE = "account,project,tax_rate"
        ACCOUNT_TAX_RATE = "account,tax_rate"
        COMPANY = "company"
        COMPANY_CONTACT = "company,contact"
        COMPANY_CONTACT_TAX_RATE = "company,contact,tax_rate"
        COMPANY_TAX_RATE = "company,tax_rate"
        CONTACT = "contact"
        CONTACT_TAX_RATE = "contact,tax_rate"
        EMPLOYEE = "employee"
        EMPLOYEE_COMPANY = "employee,company"
        EMPLOYEE_COMPANY_CONTACT = "employee,company,contact"
        EMPLOYEE_COMPANY_CONTACT_TAX_RATE = "employee,company,contact,tax_rate"
        EMPLOYEE_COMPANY_TAX_RATE = "employee,company,tax_rate"
        EMPLOYEE_CONTACT = "employee,contact"
        EMPLOYEE_CONTACT_TAX_RATE = "employee,contact,tax_rate"
        EMPLOYEE_PROJECT = "employee,project"
        EMPLOYEE_PROJECT_COMPANY = "employee,project,company"
        EMPLOYEE_PROJECT_COMPANY_CONTACT = "employee,project,company,contact"
        EMPLOYEE_PROJECT_COMPANY_CONTACT_TAX_RATE = "employee,project,company,contact,tax_rate"
        EMPLOYEE_PROJECT_COMPANY_TAX_RATE = "employee,project,company,tax_rate"
        EMPLOYEE_PROJECT_CONTACT = "employee,project,contact"
        EMPLOYEE_PROJECT_CONTACT_TAX_RATE = "employee,project,contact,tax_rate"
        EMPLOYEE_PROJECT_TAX_RATE = "employee,project,tax_rate"
        EMPLOYEE_TAX_RATE = "employee,tax_rate"
        PROJECT = "project"
        PROJECT_COMPANY = "project,company"
        PROJECT_COMPANY_CONTACT = "project,company,contact"
        PROJECT_COMPANY_CONTACT_TAX_RATE = "project,company,contact,tax_rate"
        PROJECT_COMPANY_TAX_RATE = "project,company,tax_rate"
        PROJECT_CONTACT = "project,contact"
        PROJECT_CONTACT_TAX_RATE = "project,contact,tax_rate"
        PROJECT_TAX_RATE = "project,tax_rate"
        TAX_RATE = "tax_rate"
      end
    end
  end
end
