# frozen_string_literal: true

module Merge
  module Accounting
    class SalesOrders
      class ListSalesOrdersRequestExpand
        COMPANY = "company"
        COMPANY_PAYMENT_TERM = "company,payment_term"
        COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "company,payment_term,shipping_address"
        COMPANY_SHIPPING_ADDRESS = "company,shipping_address"
        CUSTOMER = "customer"
        CUSTOMER_COMPANY = "customer,company"
        CUSTOMER_COMPANY_PAYMENT_TERM = "customer,company,payment_term"
        CUSTOMER_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "customer,company,payment_term,shipping_address"
        CUSTOMER_COMPANY_SHIPPING_ADDRESS = "customer,company,shipping_address"
        CUSTOMER_PAYMENT_TERM = "customer,payment_term"
        CUSTOMER_PAYMENT_TERM_SHIPPING_ADDRESS = "customer,payment_term,shipping_address"
        CUSTOMER_SHIPPING_ADDRESS = "customer,shipping_address"
        LINES = "lines"
        LINES_COMPANY = "lines,company"
        LINES_COMPANY_PAYMENT_TERM = "lines,company,payment_term"
        LINES_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,company,payment_term,shipping_address"
        LINES_COMPANY_SHIPPING_ADDRESS = "lines,company,shipping_address"
        LINES_CUSTOMER = "lines,customer"
        LINES_CUSTOMER_COMPANY = "lines,customer,company"
        LINES_CUSTOMER_COMPANY_PAYMENT_TERM = "lines,customer,company,payment_term"
        LINES_CUSTOMER_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,customer,company,payment_term,shipping_address"
        LINES_CUSTOMER_COMPANY_SHIPPING_ADDRESS = "lines,customer,company,shipping_address"
        LINES_CUSTOMER_PAYMENT_TERM = "lines,customer,payment_term"
        LINES_CUSTOMER_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,customer,payment_term,shipping_address"
        LINES_CUSTOMER_SHIPPING_ADDRESS = "lines,customer,shipping_address"
        LINES_PAYMENT_TERM = "lines,payment_term"
        LINES_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,payment_term,shipping_address"
        LINES_SHIPPING_ADDRESS = "lines,shipping_address"
        LINES_TRACKING_CATEGORIES = "lines,tracking_categories"
        LINES_TRACKING_CATEGORIES_COMPANY = "lines,tracking_categories,company"
        LINES_TRACKING_CATEGORIES_COMPANY_PAYMENT_TERM = "lines,tracking_categories,company,payment_term"
        LINES_TRACKING_CATEGORIES_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,tracking_categories,company,payment_term,shipping_address"
        LINES_TRACKING_CATEGORIES_COMPANY_SHIPPING_ADDRESS = "lines,tracking_categories,company,shipping_address"
        LINES_TRACKING_CATEGORIES_CUSTOMER = "lines,tracking_categories,customer"
        LINES_TRACKING_CATEGORIES_CUSTOMER_COMPANY = "lines,tracking_categories,customer,company"
        LINES_TRACKING_CATEGORIES_CUSTOMER_COMPANY_PAYMENT_TERM = "lines,tracking_categories,customer,company,payment_term"
        LINES_TRACKING_CATEGORIES_CUSTOMER_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,tracking_categories,customer,company,payment_term,shipping_address"
        LINES_TRACKING_CATEGORIES_CUSTOMER_COMPANY_SHIPPING_ADDRESS = "lines,tracking_categories,customer,company,shipping_address"
        LINES_TRACKING_CATEGORIES_CUSTOMER_PAYMENT_TERM = "lines,tracking_categories,customer,payment_term"
        LINES_TRACKING_CATEGORIES_CUSTOMER_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,tracking_categories,customer,payment_term,shipping_address"
        LINES_TRACKING_CATEGORIES_CUSTOMER_SHIPPING_ADDRESS = "lines,tracking_categories,customer,shipping_address"
        LINES_TRACKING_CATEGORIES_PAYMENT_TERM = "lines,tracking_categories,payment_term"
        LINES_TRACKING_CATEGORIES_PAYMENT_TERM_SHIPPING_ADDRESS = "lines,tracking_categories,payment_term,shipping_address"
        LINES_TRACKING_CATEGORIES_SHIPPING_ADDRESS = "lines,tracking_categories,shipping_address"
        PAYMENT_TERM = "payment_term"
        PAYMENT_TERM_SHIPPING_ADDRESS = "payment_term,shipping_address"
        SHIPPING_ADDRESS = "shipping_address"
        TRACKING_CATEGORIES = "tracking_categories"
        TRACKING_CATEGORIES_COMPANY = "tracking_categories,company"
        TRACKING_CATEGORIES_COMPANY_PAYMENT_TERM = "tracking_categories,company,payment_term"
        TRACKING_CATEGORIES_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "tracking_categories,company,payment_term,shipping_address"
        TRACKING_CATEGORIES_COMPANY_SHIPPING_ADDRESS = "tracking_categories,company,shipping_address"
        TRACKING_CATEGORIES_CUSTOMER = "tracking_categories,customer"
        TRACKING_CATEGORIES_CUSTOMER_COMPANY = "tracking_categories,customer,company"
        TRACKING_CATEGORIES_CUSTOMER_COMPANY_PAYMENT_TERM = "tracking_categories,customer,company,payment_term"
        TRACKING_CATEGORIES_CUSTOMER_COMPANY_PAYMENT_TERM_SHIPPING_ADDRESS = "tracking_categories,customer,company,payment_term,shipping_address"
        TRACKING_CATEGORIES_CUSTOMER_COMPANY_SHIPPING_ADDRESS = "tracking_categories,customer,company,shipping_address"
        TRACKING_CATEGORIES_CUSTOMER_PAYMENT_TERM = "tracking_categories,customer,payment_term"
        TRACKING_CATEGORIES_CUSTOMER_PAYMENT_TERM_SHIPPING_ADDRESS = "tracking_categories,customer,payment_term,shipping_address"
        TRACKING_CATEGORIES_CUSTOMER_SHIPPING_ADDRESS = "tracking_categories,customer,shipping_address"
        TRACKING_CATEGORIES_PAYMENT_TERM = "tracking_categories,payment_term"
        TRACKING_CATEGORIES_PAYMENT_TERM_SHIPPING_ADDRESS = "tracking_categories,payment_term,shipping_address"
        TRACKING_CATEGORIES_SHIPPING_ADDRESS = "tracking_categories,shipping_address"
      end
    end
  end
end
