# frozen_string_literal: true

module Merge
  module Hris
    # - `SINGLE` - SINGLE
    #  - `MARRIED_FILING_JOINTLY` - MARRIED_FILING_JOINTLY
    #  - `MARRIED_FILING_SEPARATELY` - MARRIED_FILING_SEPARATELY
    #  - `HEAD_OF_HOUSEHOLD` - HEAD_OF_HOUSEHOLD
    #  - `QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD` -
    #  QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD
    class MaritalStatusEnum
      SINGLE = "SINGLE"
      MARRIED_FILING_JOINTLY = "MARRIED_FILING_JOINTLY"
      MARRIED_FILING_SEPARATELY = "MARRIED_FILING_SEPARATELY"
      HEAD_OF_HOUSEHOLD = "HEAD_OF_HOUSEHOLD"
      QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD = "QUALIFYING_WIDOW_OR_WIDOWER_WITH_DEPENDENT_CHILD"
    end
  end
end
