# frozen_string_literal: true

module Merge
  module Accounting
    module PurchaseOrders
      # @type [Hash{String => String}]
      PURCHASE_ORDERS_RETRIEVE_REQUEST_EXPAND = {
        accounting_period: "accounting_period",
        company: "company",
        company_accounting_period: "company,accounting_period",
        delivery_address: "delivery_address",
        delivery_address_accounting_period: "delivery_address,accounting_period",
        delivery_address_company: "delivery_address,company",
        delivery_address_company_accounting_period: "delivery_address,company,accounting_period",
        delivery_address_vendor: "delivery_address,vendor",
        delivery_address_vendor_accounting_period: "delivery_address,vendor,accounting_period",
        delivery_address_vendor_company: "delivery_address,vendor,company",
        delivery_address_vendor_company_accounting_period: "delivery_address,vendor,company,accounting_period",
        line_items: "line_items",
        line_items_accounting_period: "line_items,accounting_period",
        line_items_company: "line_items,company",
        line_items_company_accounting_period: "line_items,company,accounting_period",
        line_items_delivery_address: "line_items,delivery_address",
        line_items_delivery_address_accounting_period: "line_items,delivery_address,accounting_period",
        line_items_delivery_address_company: "line_items,delivery_address,company",
        line_items_delivery_address_company_accounting_period: "line_items,delivery_address,company,accounting_period",
        line_items_delivery_address_vendor: "line_items,delivery_address,vendor",
        line_items_delivery_address_vendor_accounting_period: "line_items,delivery_address,vendor,accounting_period",
        line_items_delivery_address_vendor_company: "line_items,delivery_address,vendor,company",
        line_items_delivery_address_vendor_company_accounting_period: "line_items,delivery_address,vendor,company,accounting_period",
        line_items_tracking_categories: "line_items,tracking_categories",
        line_items_tracking_categories_accounting_period: "line_items,tracking_categories,accounting_period",
        line_items_tracking_categories_company: "line_items,tracking_categories,company",
        line_items_tracking_categories_company_accounting_period: "line_items,tracking_categories,company,accounting_period",
        line_items_tracking_categories_delivery_address: "line_items,tracking_categories,delivery_address",
        line_items_tracking_categories_delivery_address_accounting_period: "line_items,tracking_categories,delivery_address,accounting_period",
        line_items_tracking_categories_delivery_address_company: "line_items,tracking_categories,delivery_address,company",
        line_items_tracking_categories_delivery_address_company_accounting_period: "line_items,tracking_categories,delivery_address,company,accounting_period",
        line_items_tracking_categories_delivery_address_vendor: "line_items,tracking_categories,delivery_address,vendor",
        line_items_tracking_categories_delivery_address_vendor_accounting_period: "line_items,tracking_categories,delivery_address,vendor,accounting_period",
        line_items_tracking_categories_delivery_address_vendor_company: "line_items,tracking_categories,delivery_address,vendor,company",
        line_items_tracking_categories_delivery_address_vendor_company_accounting_period: "line_items,tracking_categories,delivery_address,vendor,company,accounting_period",
        line_items_tracking_categories_vendor: "line_items,tracking_categories,vendor",
        line_items_tracking_categories_vendor_accounting_period: "line_items,tracking_categories,vendor,accounting_period",
        line_items_tracking_categories_vendor_company: "line_items,tracking_categories,vendor,company",
        line_items_tracking_categories_vendor_company_accounting_period: "line_items,tracking_categories,vendor,company,accounting_period",
        line_items_vendor: "line_items,vendor",
        line_items_vendor_accounting_period: "line_items,vendor,accounting_period",
        line_items_vendor_company: "line_items,vendor,company",
        line_items_vendor_company_accounting_period: "line_items,vendor,company,accounting_period",
        tracking_categories: "tracking_categories",
        tracking_categories_accounting_period: "tracking_categories,accounting_period",
        tracking_categories_company: "tracking_categories,company",
        tracking_categories_company_accounting_period: "tracking_categories,company,accounting_period",
        tracking_categories_delivery_address: "tracking_categories,delivery_address",
        tracking_categories_delivery_address_accounting_period: "tracking_categories,delivery_address,accounting_period",
        tracking_categories_delivery_address_company: "tracking_categories,delivery_address,company",
        tracking_categories_delivery_address_company_accounting_period: "tracking_categories,delivery_address,company,accounting_period",
        tracking_categories_delivery_address_vendor: "tracking_categories,delivery_address,vendor",
        tracking_categories_delivery_address_vendor_accounting_period: "tracking_categories,delivery_address,vendor,accounting_period",
        tracking_categories_delivery_address_vendor_company: "tracking_categories,delivery_address,vendor,company",
        tracking_categories_delivery_address_vendor_company_accounting_period: "tracking_categories,delivery_address,vendor,company,accounting_period",
        tracking_categories_vendor: "tracking_categories,vendor",
        tracking_categories_vendor_accounting_period: "tracking_categories,vendor,accounting_period",
        tracking_categories_vendor_company: "tracking_categories,vendor,company",
        tracking_categories_vendor_company_accounting_period: "tracking_categories,vendor,company,accounting_period",
        vendor: "vendor",
        vendor_accounting_period: "vendor,accounting_period",
        vendor_company: "vendor,company",
        vendor_company_accounting_period: "vendor,company,accounting_period"
      }.frozen
    end
  end
end
