# frozen_string_literal: true

module Merge
  module Ats
    # * `YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY` -
    #  YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY
    #  * `NO_I_DONT_HAVE_A_DISABILITY` - NO_I_DONT_HAVE_A_DISABILITY
    #  * `I_DONT_WISH_TO_ANSWER` - I_DONT_WISH_TO_ANSWER
    class DisabilityStatusEnum
      YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY = "YES_I_HAVE_A_DISABILITY_OR_PREVIOUSLY_HAD_A_DISABILITY"
      NO_I_DONT_HAVE_A_DISABILITY = "NO_I_DONT_HAVE_A_DISABILITY"
      I_DONT_WISH_TO_ANSWER = "I_DONT_WISH_TO_ANSWER"
    end
  end
end
