# frozen_string_literal: true

module Merge
  module Ats
    # - `AMERICAN_INDIAN_OR_ALASKAN_NATIVE` - AMERICAN_INDIAN_OR_ALASKAN_NATIVE
    #  - `ASIAN` - ASIAN
    #  - `BLACK_OR_AFRICAN_AMERICAN` - BLACK_OR_AFRICAN_AMERICAN
    #  - `HISPANIC_OR_LATINO` - HISPANIC_OR_LATINO
    #  - `WHITE` - WHITE
    #  - `NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER` -
    #  NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER
    #  - `TWO_OR_MORE_RACES` - TWO_OR_MORE_RACES
    #  - `DECLINE_TO_SELF_IDENTIFY` - DECLINE_TO_SELF_IDENTIFY
    class RaceEnum
      AMERICAN_INDIAN_OR_ALASKAN_NATIVE = "AMERICAN_INDIAN_OR_ALASKAN_NATIVE"
      ASIAN = "ASIAN"
      BLACK_OR_AFRICAN_AMERICAN = "BLACK_OR_AFRICAN_AMERICAN"
      HISPANIC_OR_LATINO = "HISPANIC_OR_LATINO"
      WHITE = "WHITE"
      NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER = "NATIVE_HAWAIIAN_OR_OTHER_PACIFIC_ISLANDER"
      TWO_OR_MORE_RACES = "TWO_OR_MORE_RACES"
      DECLINE_TO_SELF_IDENTIFY = "DECLINE_TO_SELF_IDENTIFY"
    end
  end
end
