name: Publish Ruby Gem

on: [push]

jobs:
  build-and-publish:
    name: Build and publish Gem to RubyGems
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true

    - name: Build and Push Gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEM_API_KEY }}
      run: >-
        gem build merge_ruby_client.gemspec
        gem push merge_ruby_client-*.gem --host https://rubygems.org
